#!/bin/bash

#Remove Movies
rm "Media/Video/Movies/Horror/Amusement (HD).mp4"
rm "Media/Video/Movies/Documentary/An Inconvenient Truth.m4v"
rm "Media/Video/Movies/Sci Fi/Battlestar Galactica - Caprica.m4v"
rm "Media/Video/Movies/Crime/Best Laid Plans.m4v"
rm "Media/Video/Movies/Comedy/Broken Flowers.m4v"
rm "Media/Video/Movies/Thriller/Buried (HD).mp4"
rm "Media/Video/Movies/Drama/Dare (HD).mp4"
rm "Media/Video/Movies/Horror/Dark Water (HD).mp4"
rm "Media/Video/Movies/Comedy/Death at a Funeral (2007).m4v"
rm "Media/Video/Movies/Horror/Frailty.m4v"
rm "Media/Video/Movies/Comedy/Hot Tub Time Machine (HD).mp4"
rm "Media/Video/Movies/Horror/Let Me In (HD).mp4"
rm "Media/Video/Movies/Romantic Comedy/Management (HD).mp4"
rm "Media/Video/Movies/Drama/Memoirs of a Geisha (HD).mp4"
rm "Media/Video/Movies/Comedy/My Best Friend's Wife.m4v"
rm "Media/Video/Movies/Romantic Comedy/The Back-Up Plan (HD).mp4"
rm "Media/Video/Movies/Drama/The Ghost Writer (HD).mp4"
rm "Media/Video/Movies/Romantic Comedy/The Good Guy.m4v"
rm "Media/Video/Movies/Drama/The Social Network (HD).mp4"
rm "Media/Video/Movies/Horror/The Stepfather (HD).mp4"
rm "Media/Video/Movies/Romantic Comedy/Two Weeks Notice.m4v"
rm "Media/Video/Movies/Comedy/Uptown Girls.m4v"
rm "Media/Video/Movies/Horror/When a Stranger Calls.m4v"
rm "Media/Video/Movies/Romantic Comedy/You Again (HD).mp4"

#Remove Posters
rm "Media/Posters/Amusement (HD).mp4.jpg"
rm "Media/Posters/An Inconvenient Truth.m4v.jpg"
rm "Media/Posters/Battlestar Galactica - Caprica.m4v.jpg"
rm "Media/Posters/Best Laid Plans.m4v.jpg"
rm "Media/Posters/Broken Flowers.m4v.jpg"
rm "Media/Posters/Buried (HD).mp4.jpg"
rm "Media/Posters/Dare (HD).mp4.jpg"
rm "Media/Posters/Dark Water (HD).mp4.jpg"
rm "Media/Posters/Death at a Funeral (2010) (HD).mp4.jpg"
rm "Media/Posters/Death at a Funeral (2007).m4v.jpg"
rm "Media/Posters/Frailty.m4v.jpg"
rm "Media/Posters/Hot Tub Time Machine (HD).mp4.jpg"
rm "Media/Posters/Let Me In (HD).mp4.jpg"
rm "Media/Posters/Management (HD).mp4.jpg"
rm "Media/Posters/Memoirs of a Geisha (HD).mp4.jpg"
rm "Media/Posters/My Best Friend's Wife.m4v.jpg"
rm "Media/Posters/The Back-Up Plan (HD).mp4.jpg"
rm "Media/Posters/The Ghost Writer (HD).mp4.jpg"
rm "Media/Posters/The Good Guy.m4v.jpg"
rm "Media/Posters/The Social Network (HD).mp4.jpg"
rm "Media/Posters/The Stepfather (HD).mp4.jpg"
rm "Media/Posters/Two Weeks Notice.m4v.jpg"
rm "Media/Posters/Uptown Girls.m4v.jpg"
rm "Media/Posters/When a Stranger Calls.m4v.jpg"
rm "Media/Posters/You Again (HD).mp4.jpg"
